### ISSUE TITLE
Cambiar 'proyectos' por 'propuestas'

### ISSUE THREAD

**Issue by trixtar** [DemocraciaEnRed/vicentelopez#112]
Esto sería a nivel global, @valenzine ?

**Comment by valenzine** [comment]
Cuando se trata de 2017-2018, son propuestas (porque las propuestas se convierten en proyectos luego de votadas). ¿Se entiende?

**Comment by trixtar** [comment]
Lo que estaría entendiendo es que en todos los lugares donde diga 'proyectos' refiriendose a ideas a ser votadas, lo cambiamos por 'propuestas'. Esto incluiría la página 'proyectos' y demases. Es así?

**Comment by valenzine** [comment]
Exacto!
