### ISSUE TITLE
Tabla DATOS - nice to have

### ISSUE THREAD

**Issue by vickyguareschi** [DemocraciaEnRed/vicentelopez#119]
La fila superior deberia ser en celeste. Sacarle las lineas negras  que dividen celdas.

**Comment by trixtar** [comment]
@vickyguareschi ya hice el pull request, fijate cómo queda la tabla sin bordes y sobre todo fijate para celular ancho 360px, en mi compu la fuente de la tabla renderea los números 0 y 8 con otra altura que los demás
