### ISSUE TITLE
Orden de propuestas

### ISSUE THREAD

**Issue by trixtar** [DemocraciaEnRed/vicentelopez#124]
En Propuestas y en Home, en la lista de barrios, "Todos los proyectos" debería quedar primero (o último) de la lista, pero se desconfiguró y ahora solo queda por orden alfabético. Reordenar para que quede primero o último.

**Comment by trixtar** [comment]
OOOK, si lo hacemos superficialmente, solo tenemos que cambiar en la base de datos el titulo del forum n° 11 a "Todas las propuestas"

Si lo hacemos en profundidad, también cambiamos el name del forum a "propuestas". Esto hace que la url también vaya a /propuestas e involucra un cambio grande en el sitio donde todo lo que diga proyectos (a nivel código) migre a propuestas

**Comment by franciclo** [comment]
esto se arregla si renombramos el foro "proyectos"
