### ISSUE TITLE
Página TOPIC VIEW (PROYECTO)

### ISSUE THREAD

**Issue by valenzine** [DemocraciaEnRed/vicentelopez#13]
- [x] No se ven los botones de share de redes sociales ( Facebook, Twitter, Link y Whatsapp)
- [x] En los comentarios del topic view el filtro que los ordena quedó como `comments.sorts.score`
- [x] al entrar al un proyecto entre el click del previo y laficha desplegada se pasa x una tercera instancia intermedia (?)
- [x] Agregar _call to action_ [Diseño](https://drive.google.com/file/d/0B6xEX-eojsTWVFlsZ0pPM3RDTEk/view)
- [x] El listado de PROYECTOS debe aparecer debajo de los comentarios, para no interrumpir la experiencia de usuario.
- [x]  El botón "Votá este proyecto"debería llevar a la sección del mapa dentro de la página del "acerca de"

**Comment by valenzine** [comment]
[Diseño ](https://drive.google.com/file/d/0B6xEX-eojsTWVFlsZ0pPM3RDTEk/view)
Incluye el botón del _call to action_

**Comment by vickyguareschi** [comment]
- [ ] Leyenda botón VOTAR. [Drive link](https://drive.google.com/open?id=0B6xEX-eojsTWU0tPZkQ1aWkxeUE)
