### ISSUE TITLE
Agregar API feed proyectos

### ISSUE THREAD

**Issue by franciclo** [DemocraciaEnRed/vicentelopez#181]
Agregar una api que acepte filtros, sorts y paginación para ver los proyectos de todos los foros que corresponden a barrios.
Los fitros serán "barrio", "año" y "estado".

**Comment by mjlescano** [comment]
Los filtros de barrios por qué valores se tendrias que hacer? `tags`? `topic.attrs.barrio`?

**Comment by franciclo** [comment]
Para ésta home va a ser necesaria una migración.
Pasaremos de tener un foro por cada barrio por un solo foro "proyectos" con un campo `topic.attrs.barrio`.
Los campos año y estado tambien estarán dentro de `topic.attrs`
