### ISSUE TITLE
Agregar API feed propuestas

### ISSUE THREAD

**Issue by franciclo** [DemocraciaEnRed/vicentelopez#182]
Agregar API feed para el foro de propuestas que permita filtrar por propuestas rechazadas.
Las propuestas rechazadas son las que tienen el campo `topic.attrs.estado === 'rechazado'`.
También debe filtrar por etiqueta.

**Comment by mjlescano** [comment]
- Tiene que tener paginación o devolvemos todos los resultados?

### Algo así?:

**Endpoint:** `GET /ext/api/propuestas`

**Query params:**
```
tags // (opcional) para poder filtrar por barrio
estado=pending|accepted|rejected // (default=pending) para poder filtrar por 'topic.attrs.estado'
```

**Comment by franciclo** [comment]
Los resultados tienen que estar paginados si.
Además de los Query Params que especificaste, debe tener la opción de ordenar los resultados, por fecha de creación y popularidad, solo más uevos y más populares.

**Comment by franciclo** [comment]
Agregar filtro por barrio (`topic.attrs.barrio`)
