### ISSUE TITLE
Copywriting (textos e indicaciones)

### ISSUE THREAD

**Issue by valenzine** [DemocraciaEnRed/vicentelopez#21]
### En apartado de Comentarios
- [ ] En "Ordenado por" dice `comments.sorts.score`

(Revisar textos en Google Docs)

**PROYECTOS POR AÑO**
- [ ] Modificar el orden del gráfico y del texto. Arriba (y primero) PRESENTADOS, LUEGO APROBADOS, y por último EJECUTADOS,
- [ ] Corregir carrusel (Falta gráfico y tiene botones).
- [ ] Aunque no tengamos los datasets hay que definir icono y lugar de descarga.

----
**Diseño**
https://drive.google.com/open?id=0B6xEX-eojsTWNGdzQmtvbF9DZm8

**Comment by franciclo** [comment]
Donde van el primero y el último texto?

**Comment by valenzine** [comment]
El primero parece ser una especie de eslógan. Supongo que es un comodin.

El último lo agregó para el "ver más" . Se me ocurre que primero y último podrían ir en el ver más.

**Comment by vickyguareschi** [comment]
Si, el primero y el último en el ver más está ok. Hacelo con texto centrado justificado y debajo de todo lo demás. De referencia toma el ancho de los otros apartados ( por ejemplo en donde voto desde donde arranca el borde del icono de lado izq hasta donde termina el texto de lado derecho) Se entiende?

**Comment by valenzine** [comment]
Está sumado el link del diseño
https://drive.google.com/open?id=0B6xEX-eojsTWNGdzQmtvbF9DZm8

**Comment by valenzine** [comment]
Ya están todos los textos.
