### ISSUE TITLE
Página DATOS

### ISSUE THREAD

**Issue by vickyguareschi** [DemocraciaEnRed/vicentelopez#25]
- [x] Cambiar gráfico de proyectos por año --> [Gráfico.svg](https://drive.google.com/open?id=0B6xEX-eojsTWOWM5c1RjVUJCVUk)
- [x] Cambiar referencias gráfico proyectos por año [Referencias.svg](https://drive.google.com/open?id=0B6xEX-eojsTWY19WRXctVXVyZzQ)

**Comment by valenzine** [comment]
- [ ] Agregar botones de descarga: [Drive](https://drive.google.com/open?id=0B6xEX-eojsTWVUM4cHdsOWh3SnM) [SVG](https://drive.google.com/open?id=0B6xEX-eojsTWX1NRN1lQV3ZSeTg)

**Comment by vickyguareschi** [comment]
- [ ] Cambiar referencia Proyectos por año por tipo (nuevo orgen según observación de Powa): [Drive](https://drive.google.com/open?id=0B6xEX-eojsTWaURSWE1Nc055cGs)

**Comment by vickyguareschi** [comment]
- [ ] Cambiar referencia de Carrusel. [Refes.svg](https://drive.google.com/open?id=0B6xEX-eojsTWazRxQ2hXQ3Y3UVk)

**Comment by vickyguareschi** [comment]
- [ ] Rediseño página de DATOS : [Drive file](https://drive.google.com/open?id=0B6xEX-eojsTWVUM4cHdsOWh3SnM)
