### ISSUE TITLE
Página LANDING

### ISSUE THREAD

**Issue by vickyguareschi** [DemocraciaEnRed/vicentelopez#3]
- [x] Aumentar tamaño de referencias debajo del carousel de los gráficos.
- [x] Los botones de barrios no deberían cambiar de tamaño en hover (chequear bordes, márgenes, etc)

**Comment by valenzine** [comment]
@vickyguareschi por favor, fijate la última nueva corrección, acerca de la asimetría.

**Comment by valenzine** [comment]
- [ ] **GRÁFICOS**: Agregar la bajada que está [en el diseño](https://drive.google.com/file/d/0B6xEX-eojsTWemVPV0VNX05jMzA/view):
> El presupuesto participativo de Vicente López se viene haciendo de manera ininterrumpida desde el 2012. Aquí encontrarás información y datos históricos de todas las ediciones de Foros Vecinales.
