### ISSUE TITLE
Revisión de README.md

### ISSUE THREAD

**Issue by mariaPazBeltran** [DemocraciaEnRed/vicentelopez#371]
_Este issue forma parte de un procesos de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID._
### Issue de revisión de documentación:
Al haber contrastado la información presentadas en el repo oficial con los campos solicitados en la plantilla de readme.md https://github.com/EL-BID/Plantilla-de-repositorio/blob/master/README.md y considerando lo conversado anteriormente, hemos encontrado los siguiente puntos a mejorar:
- [x] La documentación debe llevar el nombre de la herramienta.
- [x] Traducción de la documentación al español.
- **Descripción y contexto:**
- [x] Descripción de las funcionalidades.
- [ ] el contexto donde fue desarrollado y los problemas de desarrollo que ayudó a resolver.
- **Guía de usuario:**
- [ ] Paso a paso dirigido al usuario final sobre cómo empezar a usar la herramienta digital.
_El objetivo de esta sección es que el usuario logre entender la herramienta de la manera más sencilla._
_Si la info. es demasiado extensa, puede ir en un doc. aparte el cual será nombrado en la documentación._
- **Guía de Instalación:**
_Esta sección va dirigida a desarrolladores por lo que se debe de especificar._
- [x] Los requisitos del sistema operativo para la compilación (versiones específicas de librerías, software de gestión de paquetes y dependencias, SDKs y compiladores, etc.).
- [x] Las dependencias propias del proyecto, tanto externas como internas (orden de compilación de sub-módulos, configuración de ubicación de librerías dinámicas, etc.).
- [x] Pasos específicos para la compilación del código fuente y ejecución de tests unitarios en caso de que el proyecto disponga de ellos.
_***Dependencias.** descripción de los recursos externos que generan una dependencia para la reutilización de la herramienta digital (librerías, frameworks, acceso a bases de datos y licencias de cada recurso)._

_Personalmente, cuando seguí la guía de instalación no pude instalar Docker por lo que me gustaría agregar unos puntos teniendo en cuenta lo ya conversado con el equipo._
- [x] Explicación del porque usar Docker junto a la herramienta.
- [x] Explicación de que hacer si el desarrollador no puede usar docker.

_***Sugerencia.** Dado que su equipo trabaja con un sistema operativo especifico, seria bueno que comprobaran si los comandos de instalación y uso de la herramienta varían dependiendo del sistema operativo del desarrollador. De esa manera a futuro se podrían hacer mejoras en la guía de instalación para el beneficio de todos los desarrolladores._

- **Cómo contribuir:**
- [x] Explicación para nuevos desarrolladores de como contribuir al Proyecto

- **Autor/es, Licencias y Código de conducta**
- [x] Las Licencias y el Código de conducta deben ser mencionadas en la documentación.
- [x] Créditos a los colaboradores de la Herramienta.

- **Secciones deseables.**
- [x] **Insignias (badges).**
- [x] **Versión/es** indica un listado de las versiones de las herramientas digital y las funcionalidades añadidas a cada versión.
- [x] Reconocimientos a personas u organizaciones que hayan contribuido de alguna forma al proyecto

**Comment by mariaPazBeltran** [comment]
Si existe algún Problema con alguno de los puntos anteriores, diganme.

**Comment by Veronidas** [comment]
> _Este issue forma parte de un procesos de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID._
> 
> ### Issue de revisión de documentación:
> Al haber contrastado la información presentadas en el repo oficial con los campos solicitados en la plantilla de readme.md https://github.com/EL-BID/Plantilla-de-repositorio/blob/master/README.md y considerando lo conversado anteriormente, hemos encontrado los siguiente puntos a mejorar:
> 
> * [ ]  La documentación debe llevar el nombre de la herramienta.
> * [x]  Traducción de la documentación al español.
> * **Descripción y contexto:**
> * [ ]  Descripción de las funcionalidades.
> * [ ]  el contexto donde fue desarrollado y los problemas de desarrollo que ayudó a resolver.
> * **Guía de usuario:**
> * [ ]  Paso a paso dirigido al usuario final sobre cómo empezar a usar la herramienta digital.
>   _El objetivo de esta sección es que el usuario logre entender la herramienta de la manera más sencilla._
>   _Si la info. es demasiado extensa, puede ir en un doc. aparte el cual será nombrado en la documentación._
> * **Guía de Instalación:**
>   _Esta sección va dirigida a desarrolladores por lo que se debe de especificar._
> * [ ]  Los requisitos del sistema operativo para la compilación (versiones específicas de librerías, software de gestión de paquetes y dependencias, SDKs y compiladores, etc.).
> * [ ]  Las dependencias propias del proyecto, tanto externas como internas (orden de compilación de sub-módulos, configuración de ubicación de librerías dinámicas, etc.).
> * [ ]  Pasos específicos para la compilación del código fuente y ejecución de tests unitarios en caso de que el proyecto disponga de ellos.
>   _***Dependencias.** descripción de los recursos externos que generan una dependencia para la reutilización de la herramienta digital (librerías, frameworks, acceso a bases de datos y licencias de cada recurso)._
> 
> _Personalmente, cuando seguí la guía de instalación no pude instalar Docker por lo que me gustaría agregar unos puntos teniendo en cuenta lo ya conversado con el equipo._
> 
> * [ ]  Explicación del porque usar Docker junto a la herramienta.
> * [ ]  Explicación de que hacer si el desarrollador no puede usar docker.
> 
> _***Sugerencia.** Dado que su equipo trabaja con un sistema operativo especifico, seria bueno que comprobaran si los comandos de instalación y uso de la herramienta varían dependiendo del sistema operativo del desarrollador. De esa manera a futuro se podrían hacer mejoras en la guía de instalación para el beneficio de todos los desarrolladores._
> 
> * **Cómo contribuir:**
> * [ ]  Explicación para nuevos desarrolladores de como contribuir al Proyecto
> * **Autor/es, Licencias y Código de conducta**
> * [ ]  Las Licencias y el Código de conducta deben ser mencionadas en la documentación.
> * [ ]  Créditos a los colaboradores de la Herramienta.
> * **Secciones deseables.**
> * [ ]  **Insignias (badges).**
> * [ ]  **Versión/es** indica un listado de las versiones de las herramientas digital y las funcionalidades añadidas a cada versión.
> * [ ]  Reconocimientos a personas u organizaciones que hayan contribuido de alguna forma al proyecto

Lista la traducción, a la espera de revisión: https://docs.google.com/document/d/1fX3xJcijy-Gaut8Jwgtr1Wei_VdVjCZN8oL-npT55as/edit?usp=sharing

**Comment by guillecro** [comment]
Cierro el issue con la idea de que hemos cumplido con lo requerido.
