### ISSUE TITLE
Revisión de evaluación técnica. 

### ISSUE THREAD

**Issue by mariaPazBeltran** [DemocraciaEnRed/vicentelopez#372]
_Este issue forma parte de un procesos de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID._
## Issue de evaluación técnica:
Al haber contrastado la información presentadas en el repo oficial hemos encontrado los siguiente puntos a mejorar:
- [x] Agregar el microservicio de reportes de evaluación estática de código de Sonarcloud. Tenga en cuenta que las condiciones ideales del reporte son:
>         1 Ausencia de fallos estructurales
>         2 Menos del 25% de líneas duplicadas
>         3 Menos de 10 problemas críticos
>         4 Más del 50% de clases, interfaces y métodos documentados
>         5 Deuda técnica menor a 30 días
>         6 Cobertura de test más del 25%
- [x] Agregar el badge de este servicio visible en el readme.md
- [ ] Agregar el microservicio de integración continua de código (opcional)
- [ ] Agregar el badge de este servicio visible en el readme.md (opcional)

**Comment by mariaPazBeltran** [comment]
Se cumplió con los requisitos básicos

**Comment by guillecro** [comment]
Cierro el issue con la idea de que hemos cumplido con lo requerido.
