### ISSUE TITLE
MOBILE

### ISSUE THREAD

**Issue by valenzine** [DemocraciaEnRed/vicentelopez#44]
- [x]  Corregir encabezado para width: 360px (para que quede todo en una sola línea)
- [x]  En `.thumbs.info-landing` poner font-size: 16px

**Comment by trixtar** [comment]
Qué sería el título del segundo punto?
Lo último está hecho. Lo primero lo estoy resolviendo en el issue "Menu Bar - Nav option"

**Comment by valenzine** [comment]
Se refiere a que el título "Foros Vecinales" y los barrios están demasiado grandes. Hay que pedirle a Vicky el tamaño de tipografía para esa vista en pantallas muy chicas.

**Comment by trixtar** [comment]
@vickyguareschi fijate lo del tamaño de la tipografía que dijo Valen ahi arriba
