### ISSUE TITLE
Menu bar - Nav options

### ISSUE THREAD

**Issue by vickyguareschi** [DemocraciaEnRed/vicentelopez#48]
Agregar links de navegacion al menu bar. 

[menu bar nav.pdf](https://github.com/DemocraciaEnRed/vicentelopez/files/1232114/menu.bar.nav.pdf)

**Comment by vickyguareschi** [comment]
[Estado Menu Bar nav.pdf](https://github.com/DemocraciaEnRed/vicentelopez/files/1232252/Estado.Menu.Bar.nav.pdf)

cuando se hace hover sobre la opcion se vuelve violeta ( #8C1E81 )
Cuando se esta en la seccion seleccionada se queda de color violeta (#8C1E81) hasta volver a la landing o cambiar a otra seccion

**Comment by vickyguareschi** [comment]
Menu mobile 

[MENU MOBILE .pdf](https://github.com/DemocraciaEnRed/vicentelopez/files/1232319/MENU.MOBILE.pdf)

**Comment by florlafuente** [comment]
valenzine commented a day ago • edited 

- [ ] Corregir alineación vertical y horizontal de icono de notificaciones (campanita)

- [ ] Corregir separación de caja de nav con la barra (sin espacio, tomar como referencia Consulta Pública)

<a href="https://cldup.com/2hWl2px704.png">Imagen de referencia</a>
