### ISSUE TITLE
Topic con autor 

### ISSUE THREAD

**Issue by vickyguareschi** [DemocraciaEnRed/vicentelopez#50]
[Topic con autor .pdf](https://github.com/DemocraciaEnRed/vicentelopez/files/1232339/Topic.con.autor.pdf)

**Comment by trixtar** [comment]
en un cuadrito verde

**Comment by trixtar** [comment]
Ya está codeado un div con el autor en el header del topic-article, pero no se renderean porque el campo author de los topics viene vacío
