### ISSUE TITLE
Sección PROYECTOS 

### ISSUE THREAD

**Issue by vickyguareschi** [DemocraciaEnRed/vicentelopez#56]
Así se vería la vista gral de todos los proyectos sin seleccionar barrio. 
[ProyectosGENERAL.pdf](https://github.com/DemocraciaEnRed/vicentelopez/files/1242479/ProyectosGENERAL.pdf)

Así sería la vista con barrio seleccionado. 
[ProyectoBARRIOSELECCIONADO.pdf](https://github.com/DemocraciaEnRed/vicentelopez/files/1242481/ProyectoBARRIOSELECCIONADO.pdf)

[SVG boton download](https://drive.google.com/open?id=0B6xEX-eojsTWRGt0OFpuYTJhUTQ)

**Comment by franciclo** [comment]
Actualizar el monto por barrio con la siguiente información:

CARAPACHAY, VILLA ADELINA y LA LUCILA -> $ 6.000.000 cada uno
VILLA MARTELLI, FLORIDA OESTE, VICENTE LÓPEZ -> $ 7.166.666 cada uno
MUNRO, FLORIDA ESTE, OLIVOS -> $ 8.500.000 cada uno
