### ISSUE TITLE
SHARE: Cambiar 'title' que aparece en las cards de Twitter y Facebook.

### ISSUE THREAD

**Issue by valenzine** [DemocraciaEnRed/vicentelopez#57]
Donde dice `| Foros Vecinales Vicente López` debe ir `| Presupuesto Participativo Vicente López`, quedando algo como `NOMBRE de PROYECTO - Presupuesto Participativo Vicente López` 

Referencia de cómo está ahora: https://cloudup.com/cCy2_WoNulc

**Comment by franciclo** [comment]
Cambiar la config en el dockerfile `SOCIALSHARE_SITE_NAME`
