### ISSUE TITLE
Presupuesto por Barrio

### ISSUE THREAD

**Issue by valenzine** [DemocraciaEnRed/vicentelopez#64]
Actualizar el monto por barrio con la siguiente información:

CARAPACHAY, VILLA ADELINA y LA LUCILA -> $ 6.000.000 cada uno
VILLA MARTELLI, FLORIDA OESTE, VICENTE LÓPEZ -> $ 7.166.666 cada uno
MUNRO, FLORIDA ESTE, OLIVOS -> $ 8.500.000 cada uno

**Comment by franciclo** [comment]
#56
