### ISSUE TITLE
Scroll-to-top button en static pages

### ISSUE THREAD

**Issue by trixtar** [DemocraciaEnRed/vicentelopez#71]
El botón de scroll-to-top no aparece en páginas tales como /s/acerca-de

**Comment by vickyguareschi** [comment]
Dejo acá el asset. Debería ir en la esquina inferior derecha del navegador web.
[Back To Top Button](https://drive.google.com/open?id=0B6xEX-eojsTWNV9rSFR6SVdhUkE)
