### ISSUE TITLE
Botones

### ISSUE THREAD

**Issue by trixtar** [DemocraciaEnRed/vicentelopez#92]
Los botones de barrios tienen que quedar en orden alfabético, y "todos los proyectos" debería ir primero o último.

[https://democraciaenred.slack.com/files/vicky/F6UBV5LBS/screen_shot_2017-08-29_at_3.42.09_am.png](url)

**Comment by florlafuente** [comment]
Corregir botón "consultar puntos de votación" en la topic view en mobile.

**Comment by trixtar** [comment]
En home-multiforum, columna "Dónde Voto", revisar el botón "CONSULTÁ TODOS LOS PUNTOS DE VOTACIÓN AQUÍ" que es medio overkill
